### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by takemiyamakoto**

### CODE REVIEW

**Comment by yves-pkstd** [comment]
Today i took a look at the implementation and code wise it looks good to me.  However once I build the project, create a test npm package with npm pack and install that npm package in a demo nodejs application I am running into many webpack related problems.  

Now of course it could be  a problem on my end, and I hope it is :),  with setup and config problems but I am curious to hear if anybody else is encountering the same problems as I am.

So what is going wrong:
- if I import the project in js or ts like  var Iroha = require("irohajs");  an error is thrown when I run my node script.
   "Type error: i is not a function" for webpack -p
  "Type error: existsSync is not a function" for webpack.   existsSync being a fs module function.

Obviously this means that something is going wrong during the packaging. 

I know that the following setting should cover that problem but for some reason it is not in my case.

`  node: {
    fs: "empty",
    net: "empty",
    tls: "empty"
  },`

The way I fixed is by using the externals webpack config setting.    By passing an array of node module paths to the externals setting, webpack leaves require() tags that import from node_modules alone. This results in a code bundle  that does not bundle node modules, for example js-sha3, but just leaves the require('js-sha3) tag in place.    After doing this I could use the iroha api in my node script.

problem and solution is decribed in great detail here: http://jlongster.com/Backend-Apps-with-Webpack--Part-I

Which brings me to the question: as this is a package for nodejs usage, do we include everything in the irohajs.bundle or just the iroha code?  Personally, I don't feel the need for a bundle that even includes vendor code.

As the web javascript client will differ greatly, grpc-web (alpha stage) or http rest by grpc-gateway is used, maybe it seems ok to just focus on node when it comes to the webpack settings or later use webpacks target setting and create a config for 'node' and one for 'web'.  Currently the target setting is missing so it defaults to web.

Would love to hear all your thoughts on this.

**Comment by theofilis** [comment]
Hi, Yves 

Your observation are very helpful.

You are right, it is wrong to include vendors library with irohajs and it would be great to have to different webpack configuration one for web and other for nodejs.

So, I write down those two issues/recommendation for webpack configuration.

- [ ] Do not include vendor libraries at irohajs bundle.
- [ ] Distinct configuration for web & nodejs client.

**Comment by theofilis** [comment]
For a parametrized webpack builds I follow that [guide](https://blog.ngconsultant.io/a-guide-to-simple-parametrized-webpack-builds-24d43fcf8ae2).

**Comment by stinger112** [comment]
PR outdated. 

New versions of official Iroha library called **iroha-lib** and hosted inside main Iroha's repo and on NPM.

**Pull request closed without merging**
