### PR TITLE
Webpack issues/recommendation 

### PR DESCRIPTION
**Pull request by theofilis**
I update webpack configuration according to Yves recommendations.

### CODE REVIEW

**Comment by oimou** [comment]
Hi, I'm Keiji. Let me make sure one thing about how to manage 3rd-party libraries.

According to `gh-pages` branch, 3rd-party libraries (`supercop.js` and `js-sha3.js`) were bundled into `./dist/iroha.js` before. And, by recent changes, 3rd-party libraries are now excluded from bundled file. (For what I've seen, this PR is a configuration for this.)

When I was looking over this PR, I found that iroha-javascript doesn't work on browser.

Steps to reproduce
---
1. `npm run build:web` and build `irohajs.js`
2. Prepare a simple html like this:

```index.html
<!DOCTYPE html>
<html>
<head>
        <!-- Load 3rd-party libraries by script tag -->
	<script src="./supercop.js"></script>
	<script src="./js-sha3.js"></script>
	<script src="./irohajs.js"></script>
</head>
<body>
	<h1>iroha web client</h1>
</body>
</html>
```

3. Open it in browser and see console outputs.

Expected
---
No error.

Actual
---

```Error
Uncaught TypeError: Cannot read property 'sha3_256' of undefined
    at Object.<anonymous> (irohajs.ts:6)
    at Object.r.exports (irohajs.js:1943)
    at r (bootstrap 77e0038…:19)
    at bootstrap 77e0038…:65
    at bootstrap 77e0038…:65
    at universalModuleDefinition:9
    at universalModuleDefinition:9
```

My system environment
---
Browser: Chrome Version 58.0.3029.81 (64-bit)
Node: v7.9.0
NPM: v4.2.0

Cause
---

The cause probably be that neither `supercop.js` nor `js-sha3.js` can be loaded by <script> tag because both supports only CommonJS style 🤔 

Solutions
---

Make `supercop.js` and `js-sha3.js` loadable as <script> tag, or Bundle these libraries into irohajs.js. It might be out of range of this PR.

Let me know if this problem is my environment's fault.

**Comment by theofilis** [comment]
I investigate how it will be preferable way to disturbed browser version of this library.

**Comment by oimou** [comment]
Thanks.

Though I proposed to modify `supercop.js` and `js-sha3.js`, it seems not so good choice. While to bundle 3rd-party libraries doesn't make sense for nodejs usage, it seems better to bundle them for browser usage in order to use the same code for both environment. (rather than to modify them)

**Comment by oimou** [comment]
If we have to modify two libraries,

## supercop.js
supercop.js was ported to JS by @GUCCI-swallow, so it seems easier to modify. 

## js-sha3
The problem is that js-sha3 is a 3rd-party library, but if we fork the repository, modification should not be so hard. Also I've searched alternative libraries of js-sha3:

* crypto-js https://github.com/brix/crypto-js
  * it says it has sha-3 impl but it actually has only Keccak (not sha-3) impl.
* Web Cryptography API (and polyfills)
  * it's preferable because browser native, but no sha-3 implementation.
* node-sha3
  * C++ native extension, so it's hard to use on browser.
  * emscripten may be able to convert it?

**Comment by oimou** [comment]
Emil told me:
> it seems that forking, adapting and sending a PR to upstream is a better alternative, because contributing to open-source is good, and also the time is moving forward.

**Pull request closed without merging**
